PALABRAS_CLAVE = [
    ("aciertos", "acierto", "acierta", "acierten"),
    ("acceso", "accedo", "accede", "accedan"),
    ("citación", "cito", "cita", "citen"),
    ("citar", "cito", "cita", "citen"),
    ("clave", "clavo", "clava", "claven"),
    ("cite", "cito", "cita", "citen"),
    ("comparar", "comparo", "compara", "comparen"),
    ("comprobar", "compruebo", "comprueba", "comprueben"),
    ("confirmar", "confirmo", "confirma", "confirmen"),
    ("conocer", "conozco", "conoce", "conozcan"),
    ("copia del material", "copio", "copia", "copien"),
    ("constatar", "constato", "constata", "constaten"),
    ("corroborar", "corroboro", "corrobora", "corroboren"),
    ("cotejar", "cotejo", "coteja", "cotejen"),
    ("cuadernillo", "cuadernillo", "cuadernillo", "cuadernillo"),
    ("examinar", "examino", "examina", "examinen"),
    ("exhibición", "exhibo", "exhiba", "exhiban"),
    ("exponer", "expongo", "expone", "expongan"),
    ("inspeccionar", "inspecciono", "inspecciona", "inspeccionen"),
    ("material", "materializo", "materializa", "materialicen"),
    ("mirar", "miro", "mira", "miren"),
    ("mostrar", "muestro", "muestra", "muestren"),
    ("revisar", "reviso", "revisa", "revisen"),
    ("validar", "valido", "valida", "validen"),
    ("ver", "veo", "ve", "vean"),
    ("verificar", "verifico", "verifica", "verifiquen"),
    ("visualizar", "visualizo", "visualiza", "visualicen"),
    ("revisión manual", "reviso manualmente",
     "revisa manualmente", "revisen manualmente"),
    ("preguntas que respondió bien", "respondió bien",
     "respondió bien", "respondieron bien"),
    ("preguntas que respondió mal", "respondió mal",
     "respondió mal", "respondieron mal"),
    ("preguntas que respondi bien", "respondí bien",
     "respondió bien", "respondieron bien"),
    ("preguntas que respondi mal", "respondí mal",
     "respondió mal", "respondieron mal")
]
